### ISSUE TITLE
Improve send/receive UX

### ISSUE THREAD

**Issue by KKA11010** [cashubtc/eNuts#112]
Description will be added here ASAP

**Comment by KKA11010** [comment]
I am working on this now

**Comment by BilligsterUser** [comment]
> I am working on this now

https://github.com/cashubtc/eNuts/issues/112#issuecomment-1630549704
https://github.com/cashubtc/eNuts/issues/5#issuecomment-1625996813

Maybe you should work on one issue and actually Close it?

**Comment by KKA11010** [comment]
@BilligsterUser for more context, take a look at the following screenshot. each step will represent a different screen in the payment process where data is handed over via nav-screen params. This will reduce the complexity of the current components (too many conditional rendering based on complicated conditions), improve the UX by reducing the amount of content in each screens and will provide the possibility to select mint swap.


![Screenshot (52)](https://github.com/cashubtc/eNuts/assets/40151034/8dd55f96-4084-4edb-b267-e9a14c4332ab)
