### ISSUE TITLE
CI: add Android build Workflow 

### ISSUE THREAD

**Issue by BilligsterUser** [cashubtc/eNuts#117]

**Comment by KKA11010** [comment]
I think this issue is related to the .apk build crashing. If yes, then I can close the one I've created. I didn't know exactly what this issue was about.

Closing this one now:  [https://github.com/cashubtc/eNuts/issues/118](https://github.com/cashubtc/eNuts/issues/118)

**Comment by KKA11010** [comment]
@BilligsterUser may you involve me in your plan regarding this issue? Will you create a PR after you reverted your changes in the main branch or how should we proceed now? Please let me know 👍
