### ISSUE TITLE
Wrong redirect pressing QR icon in contacts screen

### ISSUE THREAD

**Issue by KKA11010** [cashubtc/eNuts#131]
**Describe the bug**
QR code icon takes me back to the home screen

**To Reproduce**
1. Go to 'Contacts'
2. Click on 'QR icon' in top nav

**Expected behavior**
Redirect to QR scan screen

**Comment by swedishfrenchpress** [comment]
This is fixed. The QR code redirects to the QR scan screen. One point: There is a haptic feedback when I click the X on the QR scan screen. Is that intentional?

**Comment by KKA11010** [comment]
yes it's intentional

**Comment by swedishfrenchpress** [comment]
> 

Okay, I would suggest to remove it, closing a scan/camera screen is a routine action. Adding haptic feedback might overemphasize its importance, making the user question whether they did something wrong or more significant than intended. but just my 2 sats.

**Comment by KKA11010** [comment]
removing it now
