### ISSUE TITLE
Provide immediate input for entering an npub in the contacts screen.

### ISSUE THREAD

**Issue by KKA11010** [cashubtc/eNuts#132]
Enhance the user experience on first visit of contacts screen

**Comment by swedishfrenchpress** [comment]
The flow is seamless, and repeatedly canceling or going back doesn't cause any issues.
![IMG_0549](https://github.com/cashubtc/eNuts/assets/78821053/65997c60-7e55-48af-b265-146cdbff9219)

**Comment by swedishfrenchpress** [comment]
I noticed an aspect of our UI here that we might want to reconsider. Redirecting users from an app to an external webpage after clicking a CTA button, such as "What is Nostr," is not a common UX convention, especially for mobile apps. Maintaining a consistent user experience is one the main functions of UI, and most of our CTAs lead to in-app actions without sending users outside. A more consistent approach would be to ensure all CTAs, including this one, function similarly within the app. Here's an example of how we might be able to include the external link and maintain the CTA conventions.

![Example](https://github.com/cashubtc/eNuts/assets/78821053/ad808cd5-a554-4cb0-87ca-41f0e9010db0)
