### ISSUE TITLE
Emphatize the section "risks" in dashboard

### ISSUE THREAD

**Issue by KKA11010** [cashubtc/eNuts#134]
- "Highlighting the 'understand current risks' segment is key.. Its current placement adjacent to the transaction history seems makes it feel less important"

- "A possible improvement would be to encase 'understand current risks' within a distinct border or box below the QR/camera icon. Upon selecting this message, the existing modal would appear. This rearrangement would declutter the top section, reserving it solely for action buttons."

@swedishfrenchpress

**Comment by KKA11010** [comment]
A design is needed that we approve before making this changes

**Comment by KKA11010** [comment]
@swedishfrenchpress

I've updated the figma designs and added the current dashboard into the latest sheet.

[See current dashboard in figma](https://www.figma.com/file/GWk1KbXXSUvd7sEHlFKBvD/eNuts?type=design&node-id=330-1326&mode=design&t=rwWuOrHVpQGVYocq-0)

We can work on the layout to see what fits the best to emphatize the risks section.

**Comment by swedishfrenchpress** [comment]
@KKA11010 I added a slightly tweaked version of the home screen that emphasizes the risk in a slightly more attractive way. It's in the Figma dashboard next to your existing one.
