### ISSUE TITLE
Improve UX while scanning cashu token

### ISSUE THREAD

**Issue by KKA11010** [cashubtc/eNuts#163]

**Comment by swedishfrenchpress** [comment]
I've noticed we display the success animation when someone pastes in a token. WDYT about duplicating this when they redeem a token using a QR scan? It'd make the whole experience feel more unified.
![scan-example](https://github.com/cashubtc/eNuts/assets/78821053/30724053-a6c0-44c3-a692-6dfac8b17500)

**Comment by KKA11010** [comment]
Agreed

**Comment by swedishfrenchpress** [comment]
Works smoothly on 0.0.4!
