### ISSUE TITLE
Nostr contacts profile metadata don't load properly

### ISSUE THREAD

**Issue by KKA11010** [cashubtc/eNuts#168]
**Describe the bug**
Nostr contacts profile metadata dont load properly on initial start and after restarting the app as well.

**To Reproduce**
1. Go to 'contacts'
2. add your npub
3. See error

**Expected behavior**
Profile metadata should render properly

**Comment by KKA11010** [comment]
If anyone faces the same problem, please keep an eye on this discussion for further updates and fixes in the upcoming releases.

**Comment by pretyflaco** [comment]
Had same issue on first start. Closing and restarting app seems has fixed it and metadata populated, with exception of profile images.

**Comment by KKA11010** [comment]
> Had same issue on first start. Closing and restarting app seems has fixed it and metadata populated, with exception of profile images.

Yes, I've heard that restarting the app can help but is not a proper way. I will investigate further and provide a fix in the coming updates.

Profile pictures are currently not shown by default because there is no proxy implemented yet.

**Comment by daywalker90** [comment]
For me it just shows my contacts as raw npubs. My own profile username is shown and if i click my username is see my npub,  lnaddress and nip5 address. No images. Restarting app does not help.
