### ISSUE TITLE
foreground redeem self created token

### ISSUE THREAD

**Issue by KKA11010** [cashubtc/eNuts#170]
"Loving the app so far. One thing I noticed in case it hasn’t been brought up before. The app doesn’t seem to recognize when the token you have on your clipboard is one you created and intent to send to someone vs a token you received from someone so people might redeem their own token as I did the first time I used the app"

The app asks to redeem a token that has been created by the user itself, that makes no sense.

**Comment by swedishfrenchpress** [comment]
I've been investigating this and encountered the same error. The issue appears inconsistent; I noticed the notification reappeared after just a few minutes of inactivity. For a better user experience, I suggest always hiding this notification if the token is user-generated.
![IMG_7597](https://github.com/cashubtc/eNuts/assets/78821053/0ab4a19a-8d0d-4647-8976-11233d55b2c5)
