### ISSUE TITLE
Hide TX history also shows "no txs yet"

### ISSUE THREAD

**Issue by KKA11010** [cashubtc/eNuts#176]
It should be either one of both texts rendering, not both.

![photo_2023-09-09_01-59-16](https://github.com/cashubtc/eNuts/assets/40151034/5084401d-b352-4f63-a993-84870f07cbc7)

**Comment by swedishfrenchpress** [comment]
Just a piece of copywriting feedback here: I think it would be clearer to the user if it we used an active tone and replaced "latest transactions hidden" with "View latest transaction" because that is the action that is triggered when the user taps the text.
