### ISSUE TITLE
UI: Create invoice copy

### ISSUE THREAD

**Issue by swedishfrenchpress** [cashubtc/eNuts#179]
We received the following feedback from a user regarding the creating invoice copy.
"Hosever this part was a bit unclear. I wasnt sure if they meant sats or full bitcoins or something else."
![image](https://github.com/cashubtc/eNuts/assets/78821053/73b435fc-b124-4f49-a212-275efb84f848)

Let's review this think about ways to make this clearer.

**Comment by Egge7** [comment]
This is how I implement it on Current. ![image](https://github.com/cashubtc/eNuts/assets/80262989/be886399-226f-4a29-ab1b-933dd4a13b8b)

![image](https://github.com/cashubtc/eNuts/assets/80262989/c4ee2f28-6e9b-40b1-a8e7-6f821a7f84ec)

To native keyboard or not to is personal preference, but by putting the currency behind the input field it gets clear what you are supposed to enter.

**Comment by KKA11010** [comment]
Makes sense to show Sat. there :) also was thinking about showing the BTC format right under it, like in zeus? WDYM? 😏
![Screenshot_20230909_121558_Zeus.jpg](https://github.com/cashubtc/eNuts/assets/40151034/8f84c535-f28b-4489-bc8c-5de5e0e0a529)
