### ISSUE TITLE
UX / UI: Replace modals with bottom sheets

### ISSUE THREAD

**Issue by swedishfrenchpress** [cashubtc/eNuts#180]
I've spotted that in a few parts of our app, we're leaning on modals when maybe the slide-up bottom sheets would be a better fit. Right now, our modals kind of force users to engage because there's no easy way out. Switching to modal bottom sheets could enhance the UX since they are closer tot he thumb zone it's a more intuitive UX on mobile devices. They're also less obstructive, modals can be quite obstructive, and it's generally advised to avoid them, especially on mobile.

I also tried to streamline the copy and write in an active voice while trying to be as concise as possible.

![1](https://github.com/cashubtc/eNuts/assets/78821053/74bdb2e2-ff58-4903-8aa2-8b7dda85e817)
![2](https://github.com/cashubtc/eNuts/assets/78821053/c9ae4b0a-50e1-453a-b189-331eabaad760)
![3](https://github.com/cashubtc/eNuts/assets/78821053/fe1063ad-3074-4941-a6c5-f0635bda3bf1)

Would love to hear what you think, and any impressions you have.

Some resources: 
https://www.nngroup.com/articles/bottom-sheet/
https://blog.logrocket.com/ux-design/bottom-sheets-optimized-ux/

**Comment by KKA11010** [comment]
Yes I like the bottom sheet more. I will work on it, thank you for the feedback 🥰

**Comment by swedishfrenchpress** [comment]
> Yes I like the bottom sheet more. I will work on it, thank you for the feedback 🥰

Sweet! Any thoughts on the copy?

**Comment by KKA11010** [comment]
> > Yes I like the bottom sheet more. I will work on it, thank you for the feedback 🥰
> 
> Sweet! Any thoughts on the copy?

"I also tried to streamline the copy and write in an active voice while trying to be as concise as possible."

I don't fully understand what you mean here 🤔

**Comment by swedishfrenchpress** [comment]
For example:

“Are you sure that you want to check all the proofs?
This will check if your token are spendable and will otherwise delete them.”

VS

“Check all proofs?
This will verify if vour tokens are spendable. Unspendable tokens will be
deleted.”

I made copywriting suggestions in addition to the design.

**Comment by KKA11010** [comment]
yes, they're great, I will use them. They're shorter without loosing the meaning of the message! 👑
