### ISSUE TITLE
UI layout looks bad on smaller devices

### ISSUE THREAD

**Issue by Estrama9** [cashubtc/eNuts#183]
On smaller devices, the layout of the dashboard is causing problems and is not well designed as well as the font sizes and element sizes due to hard coded pixel amounts.

**Comment by KKA11010** [comment]
Hi, thanks for taking the time and opening an issue. Can you provide a screenshort of your problem? I don't know exactly what screen you mean and how the issue looks like for you.

**Comment by Estrama9** [comment]
![IMG_0026](https://github.com/cashubtc/eNuts/assets/124655087/4d4bb84e-1f38-4cc7-b1cf-faff2bf33fee)

**Comment by KKA11010** [comment]
I see, thanks a lot!

Which device is this?

**Comment by Estrama9** [comment]
iPhone SE 2020

**Comment by KKA11010** [comment]
Will work on it

**Comment by Estrama9** [comment]
Awesome. great app yours!!!
Continue the good work

**Comment by KKA11010** [comment]
> Awesome. great app yours!!! Continue the good work

Thank you, much appreciated! I can tell you that your issue here will look much worse once you have 3 transactions... I will provide a fix asap!
