### ISSUE TITLE
There is no option to change profile nostr pubkey

### ISSUE THREAD

**Issue by BrunswickBTC** [cashubtc/eNuts#184]
Reporting this as a feature request because if its there, I simply can't find it.

Once the nostr identity has been set, there appears to be no way to change it. I don't have much experience with cashu, bit it might be pertinant to let the user associate a mint with a nostr identity and switch between them on the nostr contact page.
The mint where the token is generated can therefore be determined based on which nostr identity is used to send the nut.

**Comment by KKA11010** [comment]
Thanks for reporting, this issue is related to your report and it is a work in progress 👍 

#125

**Comment by BrunswickBTC** [comment]
Thanks, I didnt notice that existing issue
