### ISSUE TITLE
"Remove mint from default" button present in non-default mint

### ISSUE THREAD

**Issue by callebtc** [cashubtc/eNuts#185]
**Describe the bug**
When having more than one mint and setting one of them to the default mint, the other mint also has the button "remove default".

**To Reproduce**
1. Add two mints
2. Make one default
3. Go to second mint and see button
4. Pressing the button removes first mint as default 

**Expected behavior**
See "make default" button on second mint.

**Comment by swedishfrenchpress** [comment]
I was able to duplicate. See recording.[https://github.com/cashubtc/eNuts/assets/78821053/41d3e0d4-3dbe-4ec5-a39d-1e2099e05926

**Comment by swedishfrenchpress** [comment]
I wasn't able to duplicate this exactly. When i toggle between setting different mints as default it seems to work. I notice another problem: the order of the mints doesn't change after one is assigned default until the user goes back to the mint a second time.

**Comment by KKA11010** [comment]
> **Describe the bug** When having more than one mint and setting one of them to the default mint, the other mint also has the button "remove default".
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Add two mints
> 
>     2. Make one default
> 
>     3. Go to second mint and see button
> 
>     4. Pressing the button removes first mint as default
> 
> 
> **Expected behavior** See "make default" button on second mint.

I tried multiple ways but wasnt able to reproduce. However, the mints are now sorted and the default is on the top of the list.
