### ISSUE TITLE
Pasting npub changes 'paste' button to 'clear'

### ISSUE THREAD

**Issue by Dawn11111111** [cashubtc/eNuts#186]
Pasting nostr npub into field changes the button from 'paste' to 'clear' to no 'enter' function available.

**To Reproduce**
1. Go to 'contacts'
2. Paste npub in field 
3. Button changes from 'paste' to 'clear'

**Expected behavior**
'Paste' function should stay or both 'paste' and 'clear' options should be available.

**Smartphone**
 - Device: Samsung Galaxy s20
 - OS: Android
 - Version: 13

**Additional context**
First time reporting an issue. Sorry if I did this poorly.

**Comment by KKA11010** [comment]
Thank you for reporting, will take care of it asap
