### ISSUE TITLE
deposit amount doubled via fake ecash deposit(backup token grabbed from clipboard)

### ISSUE THREAD

**Issue by reya01** [cashubtc/eNuts#187]
**Describe the bug**
Deposited 1k sats via lightning invoice. Then had app grab backup token from clipboard and think that backup token was another 1k ecash deposit. Now wallet shows 2k balance, 1k deposit via lightning, and 1k via ecash deposit. Only 1k deposit via lightning is real. Balance should be 1k deposit. Now cannot send ecash because I have that fake 1k via ecash deposit. 

**To Reproduce**
1. on iOS go to Options, security, create a backup token
2. exit enuts app
3. copy backup token elsewhere on iPhone
4. come back to enuts app
5. enuts app seems to have automatically grabbed backup token data from my clipboard and assumed backup token was a 1k ecash deposit
6. enuts app shows 2k balance (should be 1k) and a fake 1k ecash deposit
7. Try to hit send and send ecash, get error "tokens already spent. Secret..." 

**Expected behavior**
Should show only 1 deposit of 1k sats from lightning. Should not grab backup token from clipboard and think its an ecash deposit. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS 16.6.1

**Smartphone (please complete the following information):**
 - Device: iPhone

**Additional context**

**Comment by KKA11010** [comment]
related issue: #174
