### ISSUE TITLE
Tokens are marked as spent as soon as they are created

### ISSUE THREAD

**Issue by dtonon** [cashubtc/eNuts#193]
**Describe the bug**
Created token "vanished" without any apparent reason.
This problem has happened a couple of times, but I haven't been able to figure out how yet.

**To Reproduce**
1. Create a Token with the Send function
2. Open the token details and use "Check if token has been spent"

**Expected behavior**
The token should not be spent.

**Desktop (please complete the following information):**
 - OS: Android
 - Version apk 0.3.0

**Comment by dtonon** [comment]
**False alarm!**
I summed up all the transactions history and I there are not missing sats!

The problem is probably related to the fact che after creating a token if the user copy it eNuts is able to find it in the clipboard and shows a prompt to redeem it; is possibile that I clicked ok by error (two times? maybe).

This could be easily be mitigated by #192

**Comment by dtonon** [comment]
I was probably able to reproduce, there is a glitch in the UX.
At the end of the token creation, the user can share or copy it.
If the user copies it, the app does not immediately check the clipboard, and nothing happens.
If the user changes apps, then goes back to eNuts, uses the share button, or simply starts the share but then closes it (what I did!), eNuts proposes to redeem the token, and the user can wrongly accept.

Possible solution: do not propose to redeem tokens that are present in the app. If the user wants to redeem his own token (a less frequent situation than copying a third-party token) can simply use Receive.

**Comment by KKA11010** [comment]
Thank you for the report, I will have a look into it

**Comment by KKA11010** [comment]
> I was probably able to reproduce, there is a glitch in the UX.
> At the end of the token creation, the user can share or copy it.
> If the user copies it, the app does not immediately check the clipboard, and nothing happens.
> If the user changes apps, then goes back to eNuts, uses the share button, or simply starts the share but then closes it (what I did!), eNuts proposes to redeem the token, and the user can wrongly accept.
> 
> Possible solution: do not propose to redeem tokens that are present in the app. If the user wants to redeem his own token (a less frequent situation than copying a third-party token) can simply use Receive.

Yes that would be a better UX to not offer a redeem option when the app comes to the foreground if the token has been created by the user itself. 👍👍

**Comment by KKA11010** [comment]
I am closing this issue now.

further related discussions to "foreground auto-claiming process" can be found in #192
