### ISSUE TITLE
Unable to receive ecash token from other mint.

### ISSUE THREAD

**Issue by swedishfrenchpress** [cashubtc/eNuts#212]
**Describe the bug**
After generating a token on cashu.me, attempting to paste and redeem it on enuts results in no action. The screen dims slightly, but the token is not redeemed."

**To Reproduce**
1. Generate an ecash token on cashu.me
2. Copy the token your clipboard
3. In eNuts: Click receive -> paste & redeem Ecash

**Expected behavior**

1. The user is notified that the token is from a mint they are not currently connected to and is asked if they wish to trust it. 
2. If the user decides to trust the mint, the token should be redeemed, and a success screen should appear.

**Recording**
https://github.com/cashubtc/eNuts/assets/78821053/056c8fc4-80f3-48e0-9d0b-ffafef2a9f18

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: 16.6.1

**Comment by swedishfrenchpress** [comment]
Behavior is functioning when token from unconnected mint is redeemed via QR scanning. However, i think from a UI POV we should be a bottom sheet instead of a modal. As referenced in #180.
![IMG_0893](https://github.com/cashubtc/eNuts/assets/78821053/1b9fa43c-5349-4e07-bbca-0ad274177cc2)

**Comment by KKA11010** [comment]
I fixed it today :)
