### ISSUE TITLE
Feature request: Hide wallet balance

### ISSUE THREAD

**Issue by callebtc** [cashubtc/eNuts#226]
Pasting from an issue that was falsely submitted to the nutshell repo (https://github.com/cashubtc/cashu/issues/316):

**Description**:

Hide the wallet's balance and satoshi amounts with asterisks

**Current Behavior**:

Users only have the option to 'Hide your total balance' or 'Hide your latest transactions' in the 'Privacy' menu in 'Options'

**Expected Behavior**:

Users can choose to view or hide their balance and amounts of satoshis from the 'Wallet' screen. 

**Proposed Process**:

_From the 'Wallet' screen_

1. Tap the eNuts logo

**Comment by KKA11010** [comment]
That's a good idea and I will implement it 👍
