### ISSUE TITLE
Improve proxy profile & banner img quality

### ISSUE THREAD

**Issue by KKA11010** [cashubtc/eNuts#241]

**Comment by BilligsterUser** [comment]
we use [cloudinary](https://cloudinary.com/documentation/transformation_reference) 
@KKA11010  could you have a look an tell me how i should transform the imgs

**Comment by KKA11010** [comment]
> we use [cloudinary](https://cloudinary.com/documentation/transformation_reference) @KKA11010 could you have a look an tell me how i should transform the imgs

[cloudinary image optimization docs](https://cloudinary.com/documentation/image_optimization#how_to_optimize_image_quality)
