### ISSUE TITLE
Lnurl/lnaddress lightning payment yields negative fees, false lightning transaction history

### ISSUE THREAD

**Issue by BrunswickBTC** [cashubtc/eNuts#242]
**Describe the bug**
When sending sats via lightning address, transaction fees are misreported. Total balance is correct and when checking cashu proofs, everything appears valid.

**To Reproduce**
1. Start with cashu tokens in wallet from a lnbits cashu mint
2. Press "Send" from main screen
3. Press "Pay lightning Invoice"
4. Press "LN Invoice or LNURL"
5. Enter a lnaddress for a wallet on the same lnbits server as the mint.
6. Send 1 sat with no comment
7. Press "Estimate Fee"
8. Verify it says "Total Incl Fee 1 Satoshi"
9. Press "Continue"
10. Verify next screen indicates the same correct information.
11. Press "Cash out"
12. See screens below for example result.

Note: it appears the incorrect fee is the remainder of whichever 2^x sized cashu token the lightning amount is taken from.

**Screenshots**
Starting with zero balance, added 10 sats via cashu, then sent 1sat via lnaddress. Total balanve only shows 1sat reduction, but lightning transaction shows negative fee

![Screenshot_20231003-163358.png](https://github.com/cashubtc/eNuts/assets/139009553/dc62985e-d912-4bca-9c54-cc28bf2c2325)

![Screenshot_20231003-163408.png](https://github.com/cashubtc/eNuts/assets/139009553/c64c6709-fff5-477f-8af2-a213b0cd4e22)

**Pixel 6pro (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: GrapheneOS, android 13
 - eNuts app
 - v0.0.4

**Comment by BilligsterUser** [comment]
can we close this issue?

**Comment by KKA11010** [comment]
> can we close this issue?

Yes

**Comment by BrunswickBTC** [comment]
Works for me in latest version. Thank you!
