### ISSUE TITLE
Add Mint via QR code scan

### ISSUE THREAD

**Issue by prusnak** [cashubtc/eNuts#244]
Currently you can only add mint via typing or pasting the mint URL.

Adding mint via QR code scan that encodes mint URL would be helpful.

**Comment by KKA11010** [comment]
Great feature request. Will add it asap.

**Comment by prusnak** [comment]
I see two options where this feature can be added:
1. either to add mint dialog (replace the button Paste with two buttons: Paste Icon and QR Code Icon)
2. directly to the Scan button on the main home screen - currently the QR code scanner says "unknown data" if the mint URL is encountered

I am leaning to implementing option 1, but maybe implementing both 1 and 2 would be nice

**Comment by KKA11010** [comment]
> I see two options where this feature can be added:
> 1. either to add mint dialog (replace the button Paste with two buttons: Paste Icon and QR Code Icon)
> 2. directly to the Scan button on the main home screen - currently the QR code scanner says "unknown data" if the mint URL is encountered - we can detect mint URLs as strings that match the regexp: `https?:\/\/.*\/cashu\/api\/v1\/.*`
> 
> I am leaning to implementing option 1, but maybe implementing both 1 and 2 would be nice

Yes, both is better. Just need to consider and validate the mint urls in the scanning screen.

Adding a qr icon in the mint screen which opens the same scanning screen can be done very quickly.
