### ISSUE TITLE
Mint invoice is lost after going back without paying

### ISSUE THREAD

**Issue by KKA11010** [cashubtc/eNuts#245]
**Is your feature request related to a problem? Please describe.**
When the mint creates an invoice and I leave the screen without paying it, I cant open the pending invoice anymore.

**Describe the solution you'd like**
Add a pending invoice to the history so that I can re-open it and display the QR to scan it at a later point in time or manually check the payment status.

**Comment by swedishfrenchpress** [comment]
A couple questions.

1.Currently, when an invoice expires, it becomes non-payable. To enhance the utility of this feature, should we consider eliminating the 10-minute LN invoice duration? I'm not sure about the potential engineering challenges this might introduce. I'm not clear if it would require the mint to maintain a constant connection or to keep the invoice 'alive'. My concern with keeping the expiration is that It would be counterproductive to allow users to view old invoices or verify the payment status but prevent them from making a payment due to an expired invoice.
2.If we choose to produce static lightning invoices with no expiration, could we adopt the Phoenix model? This would entail a permanent QR code or LN invoice that doesn't expire, giving users the flexibility to modify the amount and description.
![IMG_1350](https://github.com/cashubtc/eNuts/assets/78821053/d865701c-3358-41b1-a638-ea2c6b618354)

**Comment by KKA11010** [comment]
> A couple questions.
> 
>     1. Currently, when an invoice expires, it becomes non-payable. To enhance the utility of this feature, should we consider eliminating the 10-minute LN invoice duration? I'm not sure about the potential engineering challenges this might introduce. I'm not clear if it would require the mint to maintain a constant connection or to keep the invoice 'alive'. My concern with keeping the expiration is that It would be counterproductive to allow users to view old invoices or verify the payment status but prevent them from making a payment due to an expired invoice.
> 
>     2. If we choose to produce static lightning invoices with no expiration, could we adopt the Phoenix model? This would entail a permanent QR code or LN invoice that doesn't expire, giving users the flexibility to modify the amount and description.
> 
>     3. What do you think about giving the user the option to "clear" pending invoices?
> 
> 
> ![IMG_1350](https://user-images.githubusercontent.com/78821053/276408547-d865701c-3358-41b1-a638-ea2c6b618354.PNG)

1. Invoices specified by BOLT11 dont support unlimited expiry times. The expiry time iss typically set by the person or service generating the invoice (The mint in cases of minting or your ln wallet in cases of melting). I think that setting very long expiry times is also not recommended.

2. Phoenix wallet has BOLT12 implemented but dont count me on that, I am not sure.

I would suggest to add the lightning invoice to the history immediatly after beeing created with the status pending. Either it should update automatically or manually with a user action. The user could then re-open the invoice qr code and pay at a later point in time. Once it is paid, the status would change to what we already have in eNuts history screen: "outgoing or incoming lightning tx".

Once it expires without beeing paid, i think about removing it from the history and adding another section with expired/failed transactions to provide the functionality of re-creating that specific tx instead of having to redo all the payment process.

The expired/failed history would be displayed by using this kind of menu in the nav of the history screen: 

![photo_2023-10-19_08-49-13](https://github.com/cashubtc/eNuts/assets/40151034/80d320a0-4fe7-4f2e-b872-b2ff62b41c85)
![photo_2023-10-19_08-49-19](https://github.com/cashubtc/eNuts/assets/40151034/da272cd3-184e-493f-8b71-36329f175a55)

**Comment by swedishfrenchpress** [comment]
I'd like to present an initial concept. Although I'm still refining some ideas, I welcome any feedback on the progress I've made:

1. In this prototype, pending invoices (those that are unexpired and unpaid) are indicated with a clock icon. On the Home Screen, there's an example of a pending lightning invoice marked with a pending icon.
2. When the user accesses the transaction history, both completed and pending invoices are presented in the default view.
3. Users can click to see a list of expired invoices by tapping on the additional settings icon at the top right. Currently, these are displayed by time generated, but I'm rethinking if this is the most intuitive display method.
4. After tapping on expired invoice users have the option to regenerate the invoice. This action re-creates the specific transaction and produces a new invoice.
 
I'd be grateful for any thoughts or feedback. I'd like to refine this a bit more and eventually do some user testing.

https://github.com/cashubtc/eNuts/assets/78821053/a8d09e06-a407-4320-9576-5ae29f3ac2f0
