### ISSUE TITLE
"Stop writing "NOSTR" in all caps, what are you doing!" -fiatjaf

### ISSUE THREAD

**Issue by KKA11010** [cashubtc/eNuts#247]

**Comment by derekross** [comment]
Approved.

**Comment by KKA11010** [comment]
> Wait... is NOSTR not an acronym? Aren't acronyms written in all caps?

Yes, I guess fiatjaf feels like the writing is yelling at him! We should switch to 'nostr' to calm him down maybe?

**Comment by KKA11010** [comment]
"The Nostr"

**Comment by swedishfrenchpress** [comment]
![101](https://github.com/cashubtc/eNuts/assets/78821053/cb380979-a472-40ba-ac36-0905ee9fba76)
🫡
