### ISSUE TITLE
QR code scanner does not recognize LNURL

### ISSUE THREAD

**Issue by prusnak** [cashubtc/eNuts#248]
I think it should :-) 

Both with and without the `lightning:` prefix

**Comment by DoktorShift** [comment]
i can add it also does not work when copy paste raw LNURL. i tryed both, with and without prefix `lightning:`

**Comment by dadofsambonzuki** [comment]
+1

Does not scan nor can you paste in the LNURL string.

![Screenshot_20240209-135544.png](https://github.com/cashubtc/eNuts/assets/87125117/e0f8c7e3-0244-4276-8025-427a4718e367)

![Screenshot_20240209-135626.png](https://github.com/cashubtc/eNuts/assets/87125117/08a07584-7c3f-4ebc-b75f-13604bf0539e)

**Comment by KKA11010** [comment]
> +1
> 
> Does not scan nor can you paste in the LNURL string.
> 
> ![Screenshot_20240209-135544.png](https://github.com/cashubtc/eNuts/assets/87125117/e0f8c7e3-0244-4276-8025-427a4718e367)
> 
> ![Screenshot_20240209-135626.png](https://github.com/cashubtc/eNuts/assets/87125117/08a07584-7c3f-4ebc-b75f-13604bf0539e)
> 
> 
> 
> 

Deez nutz! are unclaimable! 🥲

Will work on a patch asap. Thank you for the message 🧡

**Comment by dadofsambonzuki** [comment]
If you can scan this, cashus will literally fall onto my desk.

![PXL_20240209_140547628.MP.jpg](https://github.com/cashubtc/eNuts/assets/87125117/453b9085-dbc3-4ea6-b840-5389771ff80e)

![PXL_20240209_140745602.MP.jpg](https://github.com/cashubtc/eNuts/assets/87125117/89a49fc5-39a3-4cbd-8e8b-fe0156c86b1b)

**Comment by KKA11010** [comment]
> If you can scan this, cashus will literally fall onto my desk.
> 
> ![PXL_20240209_140547628.MP.jpg](https://github.com/cashubtc/eNuts/assets/87125117/453b9085-dbc3-4ea6-b840-5389771ff80e)
> 
> ![PXL_20240209_140745602.MP.jpg](https://github.com/cashubtc/eNuts/assets/87125117/89a49fc5-39a3-4cbd-8e8b-fe0156c86b1b)
> 
> 
> 

Woahttt 😱😍😍😍

**Comment by erskingardner** [comment]
Was poking around at this and that invoice just [seems to be invalid](https://lightningdecoder.com/LNURL1DP68GURN8GHJ7CM0WFJJUCN5VDKKZUPWDAEXWTM4WPNHYCTYV4EJ7WTZV9SNZCTXXCENWVRYXGMNYVF3XSURGVRXXFJRYVPCVF3XVDPSVCEKYEF3VCMX2D3S8Y6RSVESXQENYVR9X4NX2CTRXCMRGCE5VFSJ7MRWW4EXCER9WE5KXEF0V9CXJTMKXGHKCMN4WFKZ7335DPD9XJMCTPZXYA6SW4HH25N5XDA8WUTX8ACXJM3AXYEZVCTDDA6KUAPAX5CRQT3SYEJ82UNPW35K7M3AXYCRQVQRC0X93).

Am I missing something? I can scan other lightning addresses in eNuts without trouble.

**Comment by KKA11010** [comment]
> Am I missing something? I can scan other lightning addresses in eNuts without trouble.

Interesting. If you look at the [function](https://github.com/cashubtc/eNuts/blob/main/src/screens/QRScan/index.tsx#L85) that is used in the QR scanner screen, you will see that it can't handle the bech32-encoded LNURLs.

1. It checks the type of code to be a QR code. **Line 89**
2. It checks if the data scanned is a cashu token. **Line 94**
3. It checks if the data is either a Nostr 'nprofile...' or 'npub...' **Line 99 & Line 108**
4. It checks if the data is a URL (try to ping and add a mint url afterwards) **Line 113**
5. Try-catch to decode LN invoice 'LNBC...' **Line117**

The catch part in the 5th point is where users end up because the code fails to decode a 'LNURL...'

**Comment by dadofsambonzuki** [comment]
> Was poking around at this and that invoice just [seems to be invalid](https://lightningdecoder.com/LNURL1DP68GURN8GHJ7CM0WFJJUCN5VDKKZUPWDAEXWTM4WPNHYCTYV4EJ7WTZV9SNZCTXXCENWVRYXGMNYVF3XSURGVRXXFJRYVPCVF3XVDPSVCEKYEF3VCMX2D3S8Y6RSVESXQENYVR9X4NX2CTRXCMRGCE5VFSJ7MRWW4EXCER9WE5KXEF0V9CXJTMKXGHKCMN4WFKZ7335DPD9XJMCTPZXYA6SW4HH25N5XDA8WUTX8ACXJM3AXYEZVCTDDA6KUAPAX5CRQT3SYEJ82UNPW35K7M3AXYCRQVQRC0X93).
> 
> Am I missing something? I can scan other lightning addresses in eNuts without trouble.

I think that URL is no longer valid as I updated the BitcoinSwitch it's associated with.

**Comment by erskingardner** [comment]
> The catch part in the 5th point is where users end up because the code fails to decode a 'LNURL...'

Facepalm. I looked through that method but was trying with a LN invoice not an LNurl. If I manage to find some time I'll give it another look.
