### ISSUE TITLE
UI: Buggy Navbar behavior when adding Npub

### ISSUE THREAD

**Issue by swedishfrenchpress** [cashubtc/eNuts#285]
**Describe the bug**
When a adding a new Npub the navbar is pushed above the bottom modal input field. If the user selects the cancel option then the bottom sheet disappears but the navbar remains in the middle.

**To Reproduce**
1. Add a new npub
2. Click on cancel

**Expected behavior**
The navbar to appear the bottom and the green "add your npub" text to appear under the illustration near the middle.

**Screenshots**
https://github.com/cashubtc/eNuts/assets/78821053/88595cd1-c112-422a-b7a7-0d5d3814f547

**Smartphone (please complete the following information):**
 - Device: iphone 12
 - OS: iOS 17.2
 - Version: v 0.2.1-beta

**Comment by KKA11010** [comment]
Thanks for reporting! Will take care of this, it's a quick fix.
