### ISSUE TITLE
Failure to create/send Token

### ISSUE THREAD

**Issue by Narthx** [cashubtc/eNuts#291]
**Describe the bug**
Getting error when trying to create/send ecash "JSON parse error unexpected end of input.

**To Reproduce**
1. Send Ecash via copy and quick share.

**Screenshots**
https://github.com/cashubtc/eNuts/assets/138950900/8f8cff86-d408-417e-8a6f-c2ef4ee5a273

**Smartphone (please complete the following information):**
 - Device:IPhone 11  [e.g. iPhone6]
 - OS:16.2 [e.g. iOS8.1]
 - using the App Store ENuts current version
 

**Additional context**
See attached screenshot video
Using mints.Enuts.beta mint

**Comment by KKA11010** [comment]
The error message suggests that there is an issue with the mint connection, leading to failed network requests.

Currently, the default mint for eNuts is hosted on LNbits servers through a FREE demo service designed for testing purposes. However, it experiences frequent downtimes and is not a reliable option for production use.

**We strongly recommend testing it with small amounts and treating any deposit as a donation. Be aware that LNbits may discontinue the demo service or implement breaking changes without any prior notice.**

We will introduce a dedicated self-hosted mint asap.
