### ISSUE TITLE
Spent enuts in wallet

### ISSUE THREAD

**Issue by Azz125125** [cashubtc/eNuts#292]
I created a backup file, I tried to send enuts but it failed. When I opened enuts it said I had enuts and I accepted them, this doubled my balance. Now I can't send enuts because I have spent SATs in my wallet
![Screenshot_20240115_181829_eNuts](https://github.com/cashubtc/eNuts/assets/145245307/4c069eee-dbe3-40b0-bcb6-1ed94c60f9a0)

**Comment by KKA11010** [comment]
Hi! This issue has already been reported in the past.

Please see comments in #174 on how to fix the balance state. If you face any issues during the process or have further questions please do not hesitate to ask here.

Sorry for the inconvenience.
