### ISSUE TITLE
eNuts crashes on contacts after update

### ISSUE THREAD

**Issue by L0laL33tz** [cashubtc/eNuts#294]
Just installed eNuts v0.2.1 and noticed that the app crashes when clicking on "contacts". I ignored the pop-up notification asking me to restore my Nostr contacts after the update. After hitting "contacts", it shows a list of contacts for a fraction of a second before it crashes and takes me back to my home screen.

iPhone SE 2020
iOS 17.2.1

https://github.com/cashubtc/eNuts/assets/54821950/d4a85c8b-69a9-4246-b568-8393edd55c2d

**Comment by KKA11010** [comment]
Thank you for reporting. There is an issue during Nostr data migration after the update.

If you have skipped the popup notification, you can perform the reset by pressing options > general > contacts > reset data now

Hope it helps!
