### ISSUE TITLE
[UI bug] Can not cancel created invoice

### ISSUE THREAD

**Issue by callebtc** [cashubtc/eNuts#344]
**Describe the bug**
After creating an invoice, the user can not close the QR code view using the cancel button in the upper right corner

**To Reproduce**
1. Create invoice
2. Try to close QR code view

**Expected behavior**
Closes QR code view and returns to main screen

**Desktop (please complete the following information):**
 - OS: iOS

**Comment by KKA11010** [comment]
This should not be the case in the latest Testflght version. I am closing this issue now.
