### ISSUE TITLE
[Feature Request] support for NFC payments

### ISSUE THREAD

**Issue by lollerfirst** [cashubtc/eNuts#361]
I think Cashu android/iOS  wallets would benefit tremendously -in terms of UX- from integrating NFC payments.

Normal people don't want to copy and paste a string of text. The best they can do is scan a QR code on the device of the merchant, but that's not how it works with ecash: the merchant needs to scan the customer's device in order to get the money.

Right now you can either pay through nostr or you have to explicitly input the amount on your device and show the QR to the merchant.
Other than being inconvenient for the majority of people, you also have the potential for errors if they input the wrong amount.

With NFC, a merchant could simply create a request for payment, the customer wallet would simply ask for user confirmation and then communicate the ecash to the merchant's wallet. Less room for errors, easier payment.

**Comment by KKA11010** [comment]
Hi @lollerfirst thanks for opening the issue.

There is already a [related issue](https://github.com/cashubtc/eNuts/issues/254)
