### ISSUE TITLE
Show an error message if openLink fails

### ISSUE THREAD

**Issue by KKA11010** [cashubtc/eNuts#58]
Use catch block to show a message that opening the link does not work

[https://github.com/cashubtc/eNuts/blob/main/src/util/index.ts#L178](https://github.com/cashubtc/eNuts/blob/main/src/util/index.ts#L178)

**Comment by tarunsamanta2k20** [comment]
@KKA11010 May i work on it?

**Comment by KKA11010** [comment]
Sure! ⚡️💜

I though showing the message using the Toaster component like here for example:

State:
[https://github.com/cashubtc/eNuts/blob/test/src/components/screens/Dashboard.tsx#L37](https://github.com/cashubtc/eNuts/blob/test/src/components/screens/Dashboard.tsx#L37)

Usage example:
[https://github.com/cashubtc/eNuts/blob/test/src/components/screens/Dashboard.tsx#L113](https://github.com/cashubtc/eNuts/blob/test/src/components/screens/Dashboard.tsx#L113)

Toaster component showing the message:
[https://github.com/cashubtc/eNuts/blob/test/src/components/screens/Dashboard.tsx#L237](https://github.com/cashubtc/eNuts/blob/test/src/components/screens/Dashboard.tsx#L237)

**Comment by KKA11010** [comment]
I am thinking about moving the Toaster component to the root in the App.tsx component so we dont need to have it in all files where it is used but only in App.tsx. Then changing the state of the hook should be enough to display it. I will include the changes in the current draft [PR](https://github.com/cashubtc/eNuts/pull/57)

**Comment by KKA11010** [comment]
Hello @tarunsamanta2k20 

Are you making progress on this?

Please give me an update 💪

**Comment by tarunsamanta2k20** [comment]
@KKA11010 i am working on it.
