### ISSUE TITLE
BETA .APK & Testflight invitation-code

### ISSUE THREAD

**Issue by KKA11010** [cashubtc/eNuts#94]
@BilligsterUser, I'm mentioning and assigning you to provide an overview of my post-PR plan.

The code is nearly set for the beta release. Some remaining TODOs require discussion for further plan improvement.

**To dos:**

- [x] Generate a downloadable and installable .APK beta build, attaching it to the BETA release notes.
- [x] Proceed with the Apple Developer account and TestFlight steps.
- [x] Update ios build script and ios config with necessary app IDs and dev account IDs.
- [x] Generate an iOS .ipa build, submitting it to Apple for TestFlight release.
- [x] Add verification hashes for released apk's
- [x] Include the eNuts TestFlight invitation code in the BETA release notes.

**Production workflow**

- [x] Create an automated workflow -> Use a PR into the main branch for preview builds to test upcoming updates before merging into the main branch.
- [x] Created automated workflow -> use release tags with the format "v*" to create production builds
- [ ] Focus on crafting end-to-end tests using react-native/expo UI testing libraries.

**Additional**

- [x] Hide the hard coded test mint on production builds
- [x] Host a mint where eNuts acts as the custodian.
- [x] Establish a Lightning address (likely the enuts mint) as a developer fund for eNuts.
- [x] Implement a tipping feature within the app for eNuts using LN (and Ecash).
- [x] Create a simple website for eNuts

**Comment by radmehrk** [comment]
Ios

**Comment by Koneaboubaca** [comment]
Salut

**Comment by KKA11010** [comment]
Salut @Koneaboubaca 👋

**Comment by KKA11010** [comment]
Hello @andrew-weber, we are aproaching a beta release and I currently have no possibillity to test functionalities on iOS. I saw you are contributing while running a dev environment on your iPhone. If you have some time, I would appreciate if you

**Comment by andrew-weber** [comment]
@KKA11010 sure I can take a look. I am not too familiar with all the functionality. Would you like to me to live stream or record me navigating the app?

**Comment by KKA11010** [comment]
@andrew-weber awesome thank you! Sure that would help a lot! Play around and press all buttons that are available 😸 test the shit out of it and use the test mint.

mint, melt, send token from it and try everything out 🥇

**Comment by KKA11010** [comment]
@andrew-weber we know that scanning QR code is not working on iOS and I believe we have to provide some kind of message to the user that he has to use the iPhone camera to scan QR. I guess Apple does not allow this functionality anyway...

**Comment by KKA11010** [comment]
@andrew-weber I just got my hands on an iPhone11 and will keep it for a while. I am now able to test the app with it.

**Comment by KKA11010** [comment]
Working on the public builds now! 🥳

**Comment by KKA11010** [comment]
How to submit an ios build to app store connect: https://docs.expo.dev/submit/ios/

**Comment by KKA11010** [comment]
iOS Testflight and APK: https://enuts.cash
