### ISSUE TITLE
i18next Type-Safe Translations

### ISSUE THREAD

**Issue by KKA11010** [cashubtc/eNuts#97]
Absence of type safety for translation keys.

Consequently, if a translation resource is missing or underwent a name change, the TypeScript compiler will fail to detect it, resulting in potential errors during runtime.

Create type declaration for i18next in /typings

See solution:
- [https://locize.com/blog/i18next-typescript/](https://locize.com/blog/i18next-typescript/)
- [https://www.i18next.com/overview/typescript](https://www.i18next.com/overview/typescript)

**Comment by KKA11010** [comment]
@BilligsterUser I really need a type-safe expertise for this one. I was able to make the translations type-safe and I was happy getting errors while accessing non existing translation keys but then it resulted in translations not working at all and it just rendered the string passed on to the t() method.

 I wanted to ask if I can assign this to you?

**Comment by BilligsterUser** [comment]
> @BilligsterUser I really need a type-safe expertise for this one. I was able to make the translations type-safe and I was happy getting errors while accessing non existing translation keys but then it resulted in translations not working at all and it just rendered the string passed on to the t() method.
> 
> I wanted to ask if I can assign this to you?

do you have a code example?

**Comment by KKA11010** [comment]
@BilligsterUser I dont have the code anymore but what I did was creating a i18n.d.ts file in the /typings dir: that looked something like this:

```typescript
import { resources } from "../i18n";

declare module "i18next" {
  interface CustomTypeOptions {
    resources: typeof resources["en"].translation;
  }
}
```

**Comment by BilligsterUser** [comment]
than pls write the one you hab again

**Comment by BilligsterUser** [comment]
pls try to fix the errors https://github.com/cashubtc/eNuts/pull/110

**Comment by KKA11010** [comment]
Will have a look tomorrow
